# Site settings
title: Spidey
description: Spidey's Homepage
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Spidey
user_description: I'm a Student from India, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Cryptocurrency.
user_title: Collab Manager | Advisor | Marketing Lead
email: spidyadv@gmail.com
twitter_username: Spideyadv
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
# linkedin_username: murraco
# github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum
discord_username: 797727571328368671

exclude: ["package.json", "src", "node_modules"]
