# Site settings
title: Spidey
description: Spidey's Homepage
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Spidey
user_description: Hello! Thanks for taking time out and viewing my website! Really Glad that you
find me interesting, I hope some girls also did ðŸ˜‚ðŸ˜‚(jk). Lets move on. 

So, I am 17 yrs old, Commerce Student from India. I have been working in NFT 
space for some months now, I have helped several projects some of the notable 
ones mentioned below. I have great experience in working as a Lead Collab Manager
/Collab Manager/Advisor for several projects. I have helped my clients/projects get
several collabs from the point when project is small to the point when it has become 
huge due to the collabs and other marketing efforts.I have connections in one the
the most notable projects/alpha groups in the space, Total count of projects
I am connected with would be 200 +. Many of the CMs in those projects/alphas
are my friends and dope people!! I am very systematic person, Hardworking, Hungry to
Achieve something big that's why grinding hard from this age!! I love to connect
with new people and make friends either it be web 2 or web . I am also 
Fond of music and Games and I have a gaming channel ( Only for my Web 2 FAM ).  
This might be hypocretic but I love NFTs and hate NFTs at the same time, as I rarely
mint any NFTs but I sell them ðŸ˜‚ðŸ˜‚ðŸ˜‚.
Enough of me, I guess. 
If you are a client looking for 1 spot destination for Collabs then shoot a DM on 
discord/Twitter DM Me!! 
If you are collab manager looking to do a collab contact my assistant 
SP17#9949 ( discord ). 

user_title: Collab Manager | Advisor | Marketing Lead
email: spidyadv@gmail.com
twitter_username: Spideyadv
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
# linkedin_username: murraco
# github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum
discord_username: 797727571328368671

exclude: ["package.json", "src", "node_modules"]
